### PR TITLE
Fix __api_url_params method

### PR DESCRIPTION
**Pull request by gkrasulya**
Use "&" as concatenator in `api_url` if it already has params

### CODE REVIEW

**Comment by gkrasulya** [comment]
Hi @man-c! Please check this PR, I just tried to use library, found this small issue and decided to fix it.
Would love to continue to use this lib. 
Cheers

**Comment by man-c** [comment]
Hi @gkrasulya and thanks for contibuting!
Could you please provide an example of this issue?

Cheers

**Comment by Dj3ross** [comment]
Hi!
I was checking for exactly that.
If you add some optional arguments to a request that has required ones, you end up having 2 '?' in the url.
Here is an example with the get_market_chart_by_id function, which requires 3 args, but has 1 optional, the resulting url when adding this optional arg is :
`'https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=usd&days=max?interval=daily'`
Could you please merge this PR ?
And thank you both for your work by the way ^^

pycoingecko_api_py

**Comment by man-c** [comment]
Thanks for the feedback! 
I will run some tests and merge the PR.

**Pull request merged**
