### PR TITLE
Use a list or tuple for multiple-valued arguments

### PR DESCRIPTION
**Pull request by tanoabeleyra**
I think it's easier to work with a list/tuple of values internally.

I also considered that it might be a bit tedious to use a list for single-valued params, so these two are both valid:

- `cg.get_price(ids="ethereum", **kwargs)`
- `cg.get_price(ids=["ethereum"], **kwargs)`

### CODE REVIEW

**Comment by Endogen** [comment]
To me this seems overly complicated. Why would anyone want to write
```python
cg.get_price(ids=['bitcoin', 'litecoin', 'ethereum'], vs_currencies='usd')
```
instead of
```python
cg.get_price(ids='bitcoin,litecoin,ethereum', vs_currencies='usd')
```

I would propose something like this:
```python
    def get_simple_price(self, ids, vs_currencies, **kwargs):
        """Get the current price of any cryptocurrency in
        any other supported currency that you need"""

        api_url = f'{self._base_url}simple/price?ids={ids}&vs_currencies={vs_currencies}'
        api_url = self._api_url_params(api_url, kwargs)
        return self._request(api_url)
```

**Comment by tanoabeleyra** [comment]
> Why would anyone want to write [...] instead of [...]

Most programmers would expect to use a data structure to represent a list of values that was specifically intended for that, instead of a comma-separated string which is just a spec of the CoinGecko API. They can even use something else in the future (like `;` or `|`) and every client will need to modify it's code instead of just update this wrapper (abstraction).

By the way, I was also going to open another PR to remove the method `__api_url_params()`, it can be done automatically by using the [`params`](https://2.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls) argument of `requests.get()`

**Comment by Endogen** [comment]
ok, understood. Makes sense. For me, i'd still prefer to have it like mentioned. I don't know a single API wrapper written in Python that would do it the way you mentioned it. I'd say simplicity rules. But i of course can see the benefit.

**Comment by man-c** [comment]
Hello! Thanks for contributing!
I think the most convenient would be to include both input options (comma-separated and lists). This way the input of the wrapper will be in agreement with the API and lists could be also used.
I am thinking to change the behavior of the input arguments to convert every list found (in any argument) to a comma-separated string. Because, as I checked, the API seems to support multiple comma-separated inputs at a few endpoints.

**Comment by man-c** [comment]
> By the way, I was also going to open another PR to remove the method `__api_url_params()`, it can be done automatically by using the [`params`](https://2.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls) argument.

Noted for future update. Feel free to open any PR if you wish!

**Comment by tanoabeleyra** [comment]
Great @man-c!, both options would be nice.

I opened another PR for the query params here #7.

**Pull request merged**
