### PR TITLE
Adding API_KEY (x_cg_pro_api_key) support for https://pro-api.coingecko.com/api/v3 calls (pro version)

### PR DESCRIPTION
**Pull request by nejcb1**
Add "x_cg_pro_api_key" to every call as this key is needed in coingecko pro version

### CODE REVIEW

**Comment by vilnik** [comment]
Don't we also need to update the url to https://pro-api.coingecko.com/api/v3/?

**Comment by slgero** [comment]
@vilnik Yes, if you use the pro version, the base URL should be https://pro-api.coingecko.com/api/v3/

**Comment by darklow** [comment]
Tested and works great.
The only note – I would add URL override to pro-api host if key is provided, but not a big deal, you can override it by yourself, but would make sense to have it as a part of the MR.

**Review by Nnamdi-sys — APPROVED** [review]

**Comment by adamxyzxyz** [comment]
hey guys has this been pulled into main?

**Comment by man-c** [comment]
Hi! This PR is going to be tested and released to master branch soon

**Comment by man-c** [comment]
Thanks for contributing!

**Comment by adamxyzxyz** [comment]
is this live on pypi?

**Comment by man-c** [comment]
Hello!
Just released a new version pycoingecko v2.3.0 (also on pypi) including PRO API version support. See README & CHANGELOG for more info.

**Pull request merged**
